# Generated by Django 4.2.5 on 2023-09-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productimage_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoriteproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='shop.product', verbose_name='Продукт'),
        ),
    ]
